# client_id: candidate_app
# client_secret: vuejsispower
# login: candidate_api_manager
# password: Us3oUs3M5M
 
# Пример просроченного access_token’а: a56c3787fd94d31cdbe8dc385314301d98a9b95b

@access_token = 3913123dc757ff62dc936aa08072ed66c3cfed9c
@refresh_token = fdbbc5082afb9af8f108429a0de2b4c9f8dbc8b2
@na_access_token = db1e75eb7ffa3f09c6413247b2a04e7d70be658c
# @access_token = {{na_access_token}}

# Авторизация
###
POST https://api-test.pfdo.ru/oauth2/token HTTP/1.1
Content-Type: application/json
 
{
    "grant_type": "password",
    "username": "candidate_api_manager",
    "password": "Us3oUs3M5M",
    "client_id": "candidate_app",
    "client_secret": "vuejsispower"
}

#Обновление токена
###
POST https://api-test.pfdo.ru/oauth2/token HTTP/1.1
Content-Type: application/json
 
{
    "grant_type": "refresh_token",
    "refresh_token": "a05c0b315ebcb13b54f5284b31fdaeb2621e3265",
    "client_id": "candidate_app",
    "client_secret": "vuejsispower"
}

# Создание сертификата
###
POST https://api-test.pfdo.ru/v2/certificates HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
 
{  
    "number": "9905000111",  
    "name": "Олег",  
    "soname": "Москаленко",  
    "phname": "Владимирович",  
    "messages_email": "email@gmail.com",
    "birthday":"19.04.2000"
}

# Запрос сертификата
###
GET https://api-test.pfdo.ru/v2/certificates/9905000110 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

# Активация сертификата "actual": 1 
# Деактивация "actual": 2
###
PUT https://api-test.pfdo.ru/v2/certificates/9905000111/actual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
 
{     
    "actual": 0
}

# Редактирование сертификата
###
PATCH https://api-test.pfdo.ru/v2/certificates/9905000110/personal HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{    
    "name":"О"
}

# Удаление сертификата
###
DELETE https://api-test.pfdo.ru/v2/certificates/9905000110 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
